name: QualysWASGitHub

on:
  push:
    branches:
      - master

jobs:
  Qualys_was_scan:
    runs-on: ubuntu-latest
    name: Qualys WAS Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Qualys WAS scan
        uses: Qualys/github-action-qwas@main
        id: was
        with:
          API_SERVER: ${{ vars.API_SERVER }}
          QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
          QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
          WEBAPP_ID: ${{ vars.WEBAPP_ID }}
          SCAN_NAME: ${{ vars.SCAN_NAME }}
          SCAN_TYPE: ${{ vars.SCAN_TYPE }}
          AUTH_RECORD: none
          OPTION_PROFILE: useDefault
          FAIL_ON_SCAN_ERROR: false
          WAIT_FOR_RESULT: true
          FILE_TYPE: PDF

      - name: Debug output directory
        run: |
          echo "Listing output files..."
          ls -l ./outputs || echo "No output directory found"

      - name: Upload Scan Result
        uses: actions/upload-artifact@v4
        with:
          name: Qualys_WAS_Scan_Result
          path: ./outputs/
          if-no-files-found: warn
