name: Qualys WAS Scan

on:
  push:
    branches:
      - master

jobs:
  Qualys_was_scan:
    runs-on: ubuntu-latest
    name: Qualys WAS Scan

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qualys WAS scan action step
        uses: Qualys/github-action-qwas@main
        id: was
        with:
            API_SERVER: ${{ vars.API_SERVER }}
            QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
            QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
            WEBAPP_ID: ${{ vars.WEBAPP_ID }}
            SCAN_NAME: ${{ vars.SCAN_NAME }}
            SCAN_TYPE: ${{ vars.SCAN_TYPE }}
            AUTH_RECORD: none
            OPTION_PROFILE: ${{ vars.OPTION_PROFILE }}
            OPTION_PROFILE_ID: ${{ vars.OPTION_PROFILE_ID }}
            CANCEL_OPTION: ${{ vars.CANCEL_OPTION }}
            CANCEL_HOURS: ${{ vars.CANCEL_HOURS }}
            SEVERITY_CHECK: ${{ vars.SEVERITY_CHECK }}
            SEVERITY_LEVEL: ${{ vars.SEVERITY_LEVEL }}
            EXCLUDE: ${{ vars.EXCLUDE }}
            FAIL_ON_SCAN_ERROR: False
            WAIT_FOR_RESULT: ${{ vars.WAIT_FOR_RESULT }}
            INTERVAL: ${{ vars.INTERVAL }}
            TIMEOUT: ${{ vars.TIMEOUT }}
            FILE_TYPE: ${{ vars.FILE_TYPE }}
