name: Qualys WAS Scan

on:
  push:
    branches:
      - master

jobs:
  Qualys_was_scan:
    runs-on: ubuntu-latest
    name: Qualys WAS Scan

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qualys WAS scan action step
        uses: Qualys/github-action-qwas@main
        id: was
        with:
            API_SERVER: https://qualysapi.qg3.apps.qualys.com
            QUALYS_USERNAME: rsc3sr
            QUALYS_PASSWORD: Pract1$e
            WEBAPP_ID: 907702461
            SCAN_NAME: Juice_Shop
            SCAN_TYPE: VULNERABILITY
            AUTH_RECORD: none
            OPTION_PROFILE: ${{ vars.OPTION_PROFILE }}
            OPTION_PROFILE_ID: ${{ vars.OPTION_PROFILE_ID }}
            CANCEL_OPTION: ${{ vars.CANCEL_OPTION }}
            CANCEL_HOURS: ${{ vars.CANCEL_HOURS }}
            SEVERITY_CHECK: ${{ vars.SEVERITY_CHECK }}
            SEVERITY_LEVEL: ${{ vars.SEVERITY_LEVEL }}
            EXCLUDE: ${{ vars.EXCLUDE }}
            FAIL_ON_SCAN_ERROR: False
            WAIT_FOR_RESULT: ${{ vars.WAIT_FOR_RESULT }}
            INTERVAL: ${{ vars.INTERVAL }}
            TIMEOUT: ${{ vars.TIMEOUT }}
            FILE_TYPE: ${{ vars.FILE_TYPE }}
